Repository mattermost/mattermost-plugin-confluence, pull requests merged in 2020-06, with the labels that each got.

#58 replace build-and-release workflow with ci-build
  .circleci/config.yml
Labels: 2: Dev Review, 3: QA Review

#59 Sync ci and badges
  .circleci/config.yml
  README.md
Labels: 4: Reviews Complete

#60 Add .npmrc file for save-exact packages
  webapp/.npmrc
Labels: 2: Dev Review

#61 Updates dependencies to use github.com/mattermost/mattermost-server/v5
  go.mod
  go.sum
  server/command/command.go
  server/config/main.go
  server/controller/edit_subscription.go
  server/controller/main.go
  server/controller/save_subscription.go
  server/plugin.go
  server/plugin_test.go
  server/serializer/confluence_cloud.go
  server/serializer/confluence_event.go
  server/serializer/confluence_server.go
  server/service/get_subscription_list_test.go
  server/service/get_subscription_test.go
  server/service/notification_test.go
  server/store/store.go
  server/util/util.go
Labels: 3: QA Review
