Repository mattermost/mattermost-plugin-confluence, pull requests merged in 2025-03, with the labels that each got.

#125 Refactored the code and added flow manager for Oauth setup
  server/atlassian_connect.go
  server/command.go
  server/config/main.go
  server/confluence_cloud.go
  server/confluence_server.go
  server/controller.go
  server/edit_subscription.go
  server/flow.go
  server/get_subscription.go
  server/get_subscriptions.go
  server/plugin.go
  server/plugin_test.go
  server/save_subscription.go
  server/service/confluence_service.go
Labels: 2: Dev Review

#124 [MM-57194] Mark confidential settings as secrets
  plugin.json
Labels: 2: Dev Review

#126 Added Oauth setup and connect disconnect command
  assets/templates/api/v1/oauth2/complete.html
  assets/templates/other/index.css
  assets/templates/other/message.html
  go.mod
  go.sum
  plugin.json
  server/atlassian_connect.go
  server/auth_token.go
  server/client.go
  server/client_server.go
  server/command.go
  server/config/main.go
  server/confluence_cloud.go
  server/confluence_server.go
  server/confluence_server_v2.go
  server/controller.go
  server/edit_subscription.go
  server/flow.go
  server/get_subscription.go
  server/get_subscriptions.go
  server/http.go
  server/instance_server.go
  server/notification.go
  server/oauth2.go
  server/plugin.go
  server/save_subscription.go
  server/serializer/channel_subscription.go
  server/serializer/confluence_event.go
  server/serializer/confluence_server.go
  server/serializer/page_subscription.go
  server/service/delete_subscription_test.go
  server/service/get_subscription_list.go
  server/service/get_subscription_list_test.go
  server/service/get_subscription_test.go
  server/service/save_subscription_test.go
  server/store/store.go
  server/user.go
  server/util/types/connection.go
  server/util/util.go
Labels: 2: Dev Review

#128 Added support for generic notification when user is not connected
  server/confluence_server.go
  server/notification.go
  server/serializer/channel_subscription.go
  server/serializer/page_subscription.go
Labels: 2: Dev Review, Do Not Merge

#129 Added support for using admin API token for webhook notifications
  plugin.json
  server/config/main.go
  server/confluence_cloud.go
  server/confluence_server.go
  server/flow.go
  server/notification.go
  server/plugin.go
Labels: 2: Dev Review

#133 Removed encryption for admin API token
  plugin.json
  server/config/main.go
  server/confluence_server.go
  server/plugin.go
Labels: 2: Dev Review

#134 Added Oauth and webhook support for Confluence server version greater than 9
  assets/templates/api/v1/oauth2/complete.html
  assets/templates/other/index.css
  assets/templates/other/message.html
  go.mod
  go.sum
  plugin.json
  server/atlassian_connect.go
  server/auth_token.go
  server/client.go
  server/client_server.go
  server/command.go
  server/config/main.go
  server/confluence_cloud.go
  server/confluence_server.go
  server/confluence_server_v2.go
  server/controller.go
  server/controller/confluence_server.go
  server/controller/get_subscriptions.go
  server/edit_subscription.go
  server/flow.go
  server/get_subscription.go
  server/get_subscriptions.go
  server/http.go
  server/instance_server.go
  server/notification.go
  server/oauth2.go
  server/plugin.go
  server/plugin_test.go
  server/save_subscription.go
  server/serializer/channel_subscription.go
  server/serializer/confluence_event.go
  server/serializer/confluence_server.go
  server/serializer/page_subscription.go
  server/service/confluence_service.go
  server/service/delete_subscription_test.go
  server/service/get_subscription_list.go
  server/service/get_subscription_list_test.go
  server/service/get_subscription_test.go
  server/service/save_subscription_test.go
  server/store/store.go
  server/user.go
  server/util/types/connection.go
  server/util/util.go
  webapp/src/actions/index.js
  webapp/src/actions/subscription_modal.js
  webapp/src/client/client.js
  webapp/src/constants/index.js
  webapp/src/hooks/index.js
Labels: 3: QA Review

#136 Respond to test connection
  server/confluence_server.go
Labels: 2: Dev Review

#137 Fix webhook body parsing
  server/confluence_server.go
Labels: 2: Dev Review
